#!/bin/bash
STOREPASS="spoms2022"

echo ""
echo "****************************"
echo "[AGV Manager 1 trusted store]"
echo "****************************"
echo ""
 
keytool -list -keystore AGVManager1.jks -storepass ${STOREPASS} 2>/dev/null