#!/bin/bash
STOREPASS="spoms2022"

echo ""
echo "****************************"
echo "[AGV Digital Twin 1 trusted store]"
echo "****************************"
echo ""
 
keytool -list -keystore AGVDigitalTwin1.jks -storepass ${STOREPASS} 2>/dev/null