#!/bin/bash
STOREPASS="spoms2022"

echo ""
echo "****************************"
echo "[Client App trusted store]"
echo "****************************"
echo ""
 
keytool -list -keystore ClientApp.jks -storepass ${STOREPASS} 2>/dev/null